name: Pipeline Tests

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - project/**
  


jobs:
  pipeline-tests:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: main/project/requirements.txt

    - name: Install python dependecies
      working-directory: ./main
      run: pip install -r project/requirements.txt 

    - name: Run tests
      working-directory: ./main
      run: |
        project/tests.sh