name: Pipeline Tests

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  pipeline-tests:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Run tests
      run: |
        ../project/tests.sh